CREATE TABLE pages (
  id SERIAL PRIMARY KEY,
  site_id INTEGER NOT NULL REFERENCES sites (id),
  location VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 